parameter_defaults:
  CloudName: {{ lunchbox_prov_ip }}
  ControlPlaneStaticRoutes: []
  Debug: true
  DeploymentUser: root
  DnsServers:
    - {{ lunchbox_dns }}
  DockerInsecureRegistryAddress:
    - {{ lunchbox_prov_ip }}:8787
  NeutronPublicInterface: {{ lunchbox_prov_iface }}
  NeutronDnsDomain: localdomain
  NeutronBridgeMappings: datacentre:br-ctlplane
  NeutronPhysicalBridge: br-ctlplane
  StandaloneEnableRoutedNetworks: false
  StandaloneHomeDir: /root
  StandaloneLocalMtu: 1500
