---
- block:
  - name: ensure SSH key is generated
    command: ssh-keygen -t rsa -f /root/.ssh/id_rsa -N ''
    args:
      creates: /root/.ssh/id_rsa
    tags: ssh-keys

  - name: fetch RHHI-1 ssh key
    shell: cat ~/.ssh/id_rsa.pub
    register: ssh_keys
    tags: ssh-keys

# uncomment below for troubleshooting
#  - name: verify key
#    debug: msg="{{ ssh_keys.stdout }}"
#    tags: ssh-keys

  - name: deploy keys on all servers
    authorized_key: user=root key="{{ item[0] }}"
    delegate_to: "{{ item[1] }}"
    with_nested:
      - "{{ ssh_keys.stdout }}"
      - "{{groups['lunchbox']}}"
    tags: ssh-keys
  #end block
  delegate_to: "{{node1_fqdn}}"
  run_once: true

- name: Install personal SSH public key
  authorized_key:
    user: root
    key: "{{ lookup('file', 'rnelson-homelab.pub') }}"
  tags: ssh-keys
